char_name_scrape_omit = [
    "Gangsta",
    "Darksinga",
    "Signature",
    "CharMover",
    "Bazaar",
    "Barter",
    "LDON",
    "Server",
    "Settings",
    "Errors",
    "Help",
    "Name",
    "Level",
    "Class",
    "AA",
    "HP",
    "Mana",
    "End",
    "ATK",
    "AC",
    "Haste",
    "Accuracy",
    "HP Reg.",
    "Mana Reg.",
    "Next",
    "Instagaters",
    "Savage Wolves",
    "Versus the World"
    "Prev",
    "Disciples of Hel",
    "Sanctuary",
    "This is My Swamp",
    "no guild",
    "The Nameless",
    "DOWNLOAD",
    "The Curse",
    "Abysmals End",
    "Versus the World",
    "Traders Union",
    "Renegade Ninjas",
    "Snake Fang Gang",
    "Prev",
    "Trakanon Test Club",
    "",
    "GM Test Two",
    "GM Test",
    "GM",
    "Pimps in Purp",
    "Cobra Kai",
    "INCORRECT",
    "Z",
    "Millenium",
    "New World Order",
    "Artful Death",
    "VISIT",
    "Purgatory",
    "Test Plebs",
    "test plebs",
    "Test plebs",
    "Solo Leveling",
    "PLEASE",
    "rotpvp.com"
]